name: build

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTH_STRING: ${{ secrets.AUTH_STRING_00 }}
      MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v4

      - run: ./build.sh
